### ISSUE TITLE
SDMX service not working properly

### ISSUE THREAD

**Issue by Joelcgx** [ivantapia882804/rasta12#1]
Some channels such as Star Channel, TNT, TNT Series of the SDMX service do not work correctly, they load and stop working for about 30 seconds.

**Comment by ivantapia882804** [comment]
We are testing some channels from the sdmx domain, which are functioning normally.

Previously with Bud it stopped its broadcast every 30 seconds.

On the Roku some channels that have an sdmx domain may not work correctly.

Thanks for the notice, we are working to have the best entertainment.

The thread is closed.
