### ISSUE TITLE
Canales

### ISSUE THREAD

**Issue by alancedano3** [ivantapia882804/rasta12#2]
Algunos canales de pn-tv, budlight entre otros mas estan caidos, si le actualizas te lo agradezco. Gracias

**Comment by alancedano3** [comment]
Some PN-TV channels, Budlight and more are down, if you update them I would appreciate it. Thank you

**Comment by ivantapia882804** [comment]
Lamentamos la situación que nos presentas.

Recientemente el dominio pn-tv ha vencido y expirado por el usuario, el cuál se desintegrará hasta encontrar un usuario activo.

Y de Bud ya hay canales que no se ven, pero esto es normal, ya que sólo en cualquier momento podrían reactivar lo más pronto posible.

Estamos trabajando para ofrecer mejor calidad de entretenimiento.
