### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by Joelcgx** [ivantapia882804/rasta12#3]
Todos los canales de esta direccion IP: http://45.228.234.167:8000 no funcionan.
Gracias por los canales..

**Comment by alancedano3** [comment]
es verdad pero a mi funcionan algunos (hablando como 3 o 5 nada mas) de esa direccion

**Comment by ivantapia882804** [comment]
Conclusión

La dirección web como IP que mencionas está cerrada

No hay posibilidad de reactivarlo

Se cierra el hilo
